spring:
  application:
    name: geo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bc_geo_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update