spring:
  application:
    name: telegram-bot
  datasource:
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bc_tg_bot_db
  redis:
    host: localhost
    port: 6379
    database: 1
  jackson:
    date-format: dd-MM-yyyy
    serialization:
      write-dates-as-timestamps: false
telegram:
  bot:
    keyboards:
      reply-markup:
        max-buttons-in-row:
          4
      inline:
        max-buttons-in-row:
          4
services:
  gateway-port:
    8000
  user:
    host: http://localhost
    name: users